// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/login/index.tsx";
import * as $7 from "./routes/login/oauth.ts";
import * as $8 from "./routes/login/success.tsx";
import * as $9 from "./routes/logout.ts";
import * as $10 from "./routes/signup.tsx";
import * as $$0 from "./islands/AuthFragmentCatcher.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/login/index.tsx": $6,
    "./routes/login/oauth.ts": $7,
    "./routes/login/success.tsx": $8,
    "./routes/logout.ts": $9,
    "./routes/signup.tsx": $10,
  },
  islands: {
    "./islands/AuthFragmentCatcher.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
